Ticket dop_03
dmitrylala/gos pull request #13
Opened 2023-05-09 15:09 UTC by Hoodie-Huuuuu

2023-05-09 15:12 UTC, Hoodie-Huuuuu commented
[t_dop03.pdf](https://github.com/dmitrylala/gos/files/11432608/t_dop03.pdf)
[t_dop3_small_view.pdf](https://github.com/dmitrylala/gos/files/11432627/t_dop3_small_view.pdf)

2023-05-10 11:25 UTC, dmitrylala requested changes
По содержанию все норм; есть пара технических моментов

2023-05-10 11:25 UTC, dmitrylala commented on tickets/t_dop03.tex
> +% \mathLet \ $E^m - m-$мерное евклидово пространство и в нем задано множество $\{x\}$ с элементами  $x = (x_1, x_2, ..., x_m)$. \mathLet \ каждому числу $n \in \mathbb{N}$ ставится в соответствие фун
Мб стереть, то что закомментировано, если не собираешься включать в билет?

2023-05-10 11:25 UTC, dmitrylala commented on tickets/t_dop03.tex
> +Ф.п. $\{f_n(x)\}\underset{\{x\}}{\rightrightarrows}f(x) \Leftrightarrow $ для $\forall \varepsilon > 0 \exists N(\varepsilon): |f_{n+p}(x) - f_n(x)| < \varepsilon$ при $\forall n: n \ge N(\varepsilon
- между $\forall \varepsilon > 0$ и $\exists N$ лучше поставить пробел через ~ или если побольше через \quad
- в big_view формула не оч перенеслась на следующую строку, имеет смысл ее заключить в $$ чтобы была на отдельной строке; если хочется вставлять русский текст между кванторами, это можно сделать так: '$$\formula \text{ какой-то текст } \formula \$$'

2023-05-10 11:25 UTC, dmitrylala commented on tickets/t_dop03.tex
> +
Кажется, не закоммичен \cite, в пдфке он есть

2023-05-10 11:25 UTC, dmitrylala commented on tickets/t_dop03.tex
> +% \begin{equation}
Тоже закомменчено

2023-05-10 11:25 UTC, dmitrylala commented on tickets/t_dop03.tex
> +$\bigg|\int_{a}^{b} f_n(x) \,dx - \int_{a}^{b} f(x) \,dx\bigg| = \bigg|\int_{a}^{b} [\, f_n(x) - f(x)]\,\,dx\bigg| \le \int_{a}^{b} |f_n(x) - f(x)|\,dx \le \frac{\varepsilon}{2(b-a)}\int_{a}^{b}\,dx
Эта формула тоже в big версии не оч перенеслась на следующую строку, если формула на 1 строку не помещается, можно юзать окружение \multline или \gather

2023-05-10 11:52 UTC, Hoodie-Huuuuu commented
ой задушил бля, ладно, поправлю)

2023-05-12 12:54 UTC, Hoodie-Huuuuu commented
исправленные версии
[t_dop_3_big_v
[t_dop_3_small_view.pdf](https://github.com/dmitrylala/gos/files/11464085/t_dop_3_small_view.pdf)
iew.pdf](https://github.com/dmitrylala/gos/files/11464083/t_dop_3_big_view.pdf)

пришлось сделать два файла, так как в small.tex не помещалась исправленная версия

2023-05-12 12:54 UTC, Hoodie-Huuuuu commented on tickets/t_dop03.tex
> +Ф.п. $\{f_n(x)\}\underset{\{x\}}{\rightrightarrows}f(x) \Leftrightarrow $ для $\forall \varepsilon > 0 \exists N(\varepsilon): |f_{n+p}(x) - f_n(x)| < \varepsilon$ при $\forall n: n \ge N(\varepsilon
поправил

2023-05-12 12:55 UTC, Hoodie-Huuuuu commented on tickets/t_dop03.tex
> +% \mathLet \ $E^m - m-$мерное евклидово пространство и в нем задано множество $\{x\}$ с элементами  $x = (x_1, x_2, ..., x_m)$. \mathLet \ каждому числу $n \in \mathbb{N}$ ставится в соответствие фун
поправил

2023-05-12 12:58 UTC, Hoodie-Huuuuu commented on tickets/t_dop03.tex
> +
поправил

2023-05-12 12:58 UTC, Hoodie-Huuuuu commented on tickets/t_dop03.tex
> +% \begin{equation}
поправил

2023-05-12 12:58 UTC, Hoodie-Huuuuu commented on tickets/t_dop03.tex
> +$\bigg|\int_{a}^{b} f_n(x) \,dx - \int_{a}^{b} f(x) \,dx\bigg| = \bigg|\int_{a}^{b} [\, f_n(x) - f(x)]\,\,dx\bigg| \le \int_{a}^{b} |f_n(x) - f(x)|\,dx \le \frac{\varepsilon}{2(b-a)}\int_{a}^{b}\,dx
поправил

2023-05-12 14:11 UTC, dmitrylala approved these changes

2023-05-12 14:11 UTC, merged