Ticket dop 2
dmitrylala/gos pull request #16
Opened 2023-05-11 17:02 UTC by mmariaa12

2023-05-12 08:34 UTC, dmitrylala requested changes
Добавил комментарии по содержанию и оформлению

2023-05-12 08:34 UTC, dmitrylala commented on tickets/t_dop02.tex
> +\par \textbf{Гладкая поверхность}- $\Phi$ в $Oxyz$ называется гладкой, если у каждой точки $\Phi$ есть окрестность, допускающая гладкую параметризацию, т.е. каждая указанная окрестность представляет
Мб убрать это 'гомеоморфное отображение'? Либо пояснить, что это

2023-05-12 08:34 UTC, dmitrylala commented on tickets/t_dop02.tex
> +    \dfrac{1}{\sqrt{1+{z^{\prime}}_x^2+{z^{\prime}}_y^2}}$. Таким образом: $\cos Y={-z_{y}^{\prime}}\cos Z$, $I=-\iint _{\Phi }\left( \dfrac{\partial P }{\partial z}\cdot \dfrac{\partial z}{\partial
Как это связано с определением криволинейного интеграла?

2023-05-12 08:34 UTC, dmitrylala commented on tickets/t_dop02.tex
> +%Лекции Ломова 3-4 семестр
Ссылку нужно добавить в references.bib

2023-05-12 08:34 UTC, dmitrylala commented on tickets/t_dop02.tex
> +%\begin{equation*} I=\iint _{D}\left( \int ^{z_{2}\left( x,y\right)}_{z_{1}\left( x,y\right)}\dfrac{\partial R\left( x,y,z\right)}{\partial z}dz\right)dxdy= \end{equation*} \begin{equation*} =\iint _
Мб убрать?

2023-05-12 08:34 UTC, dmitrylala commented on tickets/t_dop02.tex
> +поэтому $\cos Z \leq 0 $ и $\cos Z d\sigma=-\dfrac{1}{\sqrt{ED-F^{2}}}dxdy$. Через $\Phi _{2}$ часть поверхности $\Phi$: $z=z_{2}\left( x,y\right)$, $\left( x,y\right) \in D$, $\widehat{\left( \overr
Здесь точно в знаменателе ED - F^2? F что-то вообще до этого не было, а D так вообще вроде область

2023-05-14 14:38 UTC, mmariaa12 commented on tickets/t_dop02.tex
> +\par \textbf{Односвязная область}- область $D$ называется односвязной, если
исправила

2023-05-14 15:36 UTC, mmariaa12 commented on tickets/t_dop02.tex
> +\par \textbf{Гладкая поверхность}- $\Phi$ в $Oxyz$ называется гладкой, если у каждой точки $\Phi$ есть окрестность, допускающая гладкую параметризацию, т.е. каждая указанная окрестность представляет
убрала

2023-05-14 16:20 UTC, dmitrylala approved these changes
Исправил пару опечаток, содержание норм

2023-05-14 16:20 UTC, merged