Ticket osn23
dmitrylala/gos pull request #2
Opened 2023-05-07 10:14 UTC by alsugiliazova

2023-05-07 10:17 UTC, alsugiliazova commented
[t_osn23.pdf](https://github.com/dmitrylala/gos/files/11414701/t_osn23.pdf)
Пдф для проверки.

2023-05-08 13:28 UTC, dmitrylala requested changes

2023-05-08 13:28 UTC, dmitrylala commented on main_big.tex
> +\include{tickets/t_osn23}
В main_small также нужно раскомментить свой билет

2023-05-08 13:28 UTC, dmitrylala commented on tickets/t_osn23.tex
> +Ссылки на используемые материалы:
Для ссылок уже юзается references.bib, лучше новые ссылки добавлять сразу туда, а в билете только цитировать через \cite

2023-05-08 13:28 UTC, dmitrylala commented on tickets/t_osn23.tex
> +     & берётся с помощью бутстрепа \\
Стоит пояснить хотя бы коротко что такое бутстреп, либо заменить синонимами

2023-05-08 13:28 UTC, dmitrylala commented on tickets/t_osn23.tex
> +Главная идея бустинга – базовые алгоритмы строятся не независимо, каждый следующий мы строим так, чтобы он исправлял ошибки предыдущих и повышал качество всего ансамбля. Первый успешный вариант бусти
- AdaBoost мб вообще не стоит упоминать, если потом про него ничего не будет сказано
- Впервые вижу такой термин, как FSAM (спасибо Дьякон), мб стоит выкинуть, поскольку дальше термин не разъясняется и не очень то и нужен

2023-05-08 13:28 UTC, dmitrylala commented on tickets/t_osn23.tex
> +    \item результаты базовых алгоритмов объединяются в один с помощью обучаемой мета-модели, а не с помощью какого-либо обычного способа агрегации (суммирования или усреднения)
Второе свойство скорее = определение

2023-05-08 13:28 UTC, dmitrylala commented on tickets/t_osn23.tex
> +Простейшая схема стекинга — \textbf{блендинг} (Blending): обучающую выборку делят на две части. На первой обучают базовые алгоритмы. Затем получают их ответы на второй части и на тестовой выборке. По
- Блендинг - когда делят ровно на 2 части, или что? не оч понятно
- Также не оч понятно, каким образом блендинг здесь - простейшая схема стекинга (если считать что стекинг = умная обучаемая агрегация базовых моделей вместо глупого взятия среднего как в определении выше)

2023-05-11 08:28 UTC, merged