T_dop16
dmitrylala/gos pull request #30
Opened 2023-05-14 19:33 UTC by Fedya2006

2023-05-14 20:39 UTC, dmitrylala requested changes
- По содержанию все норм
- Проблема с референсом
- Есть чутка опечаток
- Проблемы с компиляцией при встраивании билета в общие сборки main_big и main_small

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_big.tex
> +\usepackage{vmargin}
При попытке скомпилировать main_big заинклюдив этот билет происходит крах, пишет что из-за многочисленных usepackage и begin{document} и что это делается в другом месте

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_big.tex
> +\newtheorem{lemma}{Лемма}
я так понимаю все инклюды ради этого функционала, чтобы с ними разобраться:
- стоит посмотреть в сторону уже определенного в стилевом пакете окружения definition и остальных
- либо переопределить эти окружения в этом билете и юзать уже их
- либо отказаться от них и написать всё руками как ты сделал в main_small

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_small.tex
Если скомпилить main_small с одним этим билетом то получается так:
[dop16_small.pdf](https://github.com/dmitrylala/gos/files/11472853/dop16_small.pdf)

тут тоже траблы с компиляцией, но видимо не такие очевидные, пишет такое:
- Command \textbardbl invalid in math mode on input line 23.
Возможно трабла в этом, ну или в чем-то еще

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_small.tex
> +[\cite{diffury_denisov_razg}]
Ссылка не добавлена в references.bib
Вообще там уже есть две ссылки возможно на то, что как раз и нужно:
- denisov
- denisov2
В любом случае надо либо изменить cite, либо добавить новую ссылку в references.bib если это другая книжка

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_big.tex
> +$$‖y(x)‖=\displaystyle\max_{x_0\leq x \leq x_1} |y(x)|$$
в пдфке значок нормы не отрисовался; вообще, он ставится так:
```
\|
```
либо можно юзать уже определенную в стилевом пакете команду \norm{}:
```
\norm{y(x)} -> \|y(x)\|
```

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_big.tex
> +    $y_0(x) \in M$ глобального минимума (максимума) на мж-стве $M$, если для любой $y(x) \in M$ выполнено неравенство $\Phi[y_0(x)]\leq\Phi[y(x)]  (\Phi[y_0(x)]\geq\Phi[y(x)])$.
Ты поставил пробел между ] и (, но тк это было в math mode, он не отрисовался

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_big.tex
> +    отрезке $[x_0, x_1]$. Тогда $\exists$ точка $x_2 \in (x_0, x_1):$ $f(x2)\neq0$. Пусть для определенности $f(x_2)>0$. В силу непр $f(x)$ $\exists$ $\varepsilon > 0: f(x)\geq \frac{f(x_2)}{2}>0, \f
Опечатка: 
```latex
$f(x2)$ -> $f(x_2)$
```

2023-05-14 20:39 UTC, dmitrylala commented on tickets/t_dop16_big.tex
> +\textbf{Функционал, зависящий от производных порядка выше
После этой строчки нужна пустая строка

2023-05-14 22:02 UTC, Fedya2006 commented
[t_dop16_big.pdf](https://github.com/dmitrylala/gos/files/11473026/t_dop16_big.pdf)
[t_dop16_small.pdf](https://github.com/dmitrylala/gos/files/11473027/t_dop16_small.pdf)

2023-05-14 22:13 UTC, luseno4ek commented
ИМХО  такой текст просто невозможно читать
Р-им мж-ство M, являющееся некоторым подмнож мж-ства непр на отрезке функций C[x0, x1].

Если и сокращать, то в тысячу раз лучше написать
Рассмотрим множество $M \subset C[x_0, x_1]$

Аналогично вместо 
Функционалом наз отображение мж-ства M в мж-ство действ чисел.

Сделать 
Функционал -- отображение $f: \; M \to \mathbb{R}$.

2023-05-14 22:18 UTC, luseno4ek submitted a review, later dismissed
Очень сильно не хочется оставлять билет с такими сокращениями слов, лучше переделать

2023-05-15 00:03 UTC, Fedya2006 commented
> Очень сильно не хочется оставлять билет с такими сокращениями слов, лучше переделать

[t_dop16_small (2).pdf](https://github.com/dmitrylala/gos/files/11473237/t_dop16_small.2.pdf)

2023-05-15 08:49 UTC, Fedya2006 commented
> Залей в гит актуальные версии билетов, я так понимаю в гите еще старые

Сделано

2023-05-15 10:17 UTC, dmitrylala commented
Вот так сейчас выглядит big версия:
[t_dop16_big.pdf](https://github.com/dmitrylala/gos/files/11476727/t_dop16_big.pdf)

Сокращения слов, о которых писала @luseno4ek, все еще на месте, возможно что-то не то залил

2023-05-15 10:32 UTC, dmitrylala requested changes
См. комментарий выше

2023-05-15 10:53 UTC, dmitrylala commented
Выяснили, что у оверлифа может быть трабла с компиляцией ровно 1 столбца, если скомпилить >=2 непустых столбцов на странице, то все норм (мб только у меня такое поведение)
Короче считаем, что проблема с компиляцией main_small решена

2023-05-15 10:57 UTC, dmitrylala approved these changes

2023-05-15 10:58 UTC, merged