t-dop05
dmitrylala/gos pull request #5
Opened 2023-05-08 12:23 UTC by Fedya2006

Залиты 2 версии билетов, полная(лучше с нее катать) и та, что влезает в small tex.

2023-05-08 12:56 UTC, dmitrylala requested changes
Несколько технических моментов, см. комменты
Также нужно добавить инклюд билета в main_big и main_small

2023-05-08 12:56 UTC, dmitrylala commented on t_dop05_full.tex
> +\documentclass{article}
Этот тоже

2023-05-08 12:56 UTC, dmitrylala commented on t_dop5.pdf
Пдфки пушить не надо, а для ревью лучше отдельным комментом в PR их просто прикрепить

2023-05-08 13:59 UTC, dmitrylala requested changes
Добавил комментарии по содержанию/оформлению

2023-05-08 13:59 UTC, dmitrylala commented on tickets/t_dop05_full.tex
> +\textbf{Рядом Лорана} называется функциональный ряд вида: $\sum_{n=-\infty}^{n=\infty}c_n(z-z_0)^n\text{(1)}=\sum_{n=0}^{n=\infty}c_n(z-z_0)^n + \sum_{n=-\infty}^{n=-1}c_{n}(z-z_0)^n = \sum_{n=0}^{n=
- В пдфке main_big в странном месте возникает перенос строки, из-за того что формула inline (т.е. внутри одинарных символов '$'), можно ее вставить в '$$' например
- Здесь и дальше: чтобы не писать постоянно текстом ряд.1 или ряд.2 нужно использовать \label и \ref

2023-05-08 13:59 UTC, dmitrylala commented on tickets/t_dop05_full.tex
> +\begin{definition}
Наверное, имеет смысл сначала отдельно как раз определить отдельную и главную части ряда, и про них расписать, а потом собрать их вместе и назвать результат рядом Лорана, так и ссылки будет проще организовать

2023-05-08 13:59 UTC, dmitrylala commented on tickets/t_dop05_full.tex
> +$\Longleftarrow$ : Фикс произвольную точку $z \in D$, построим вспомогательное кольцо $D'$ c тем же центром в $z_0$, $D' \subset D$ и $z \subset int(D')$. Пусть $\text{Г}_1^{'}: |\rho - z_0|=R_1'$ и
Тут в доказательстве обилие формул, читаемость без '$$' тоже оч слабая

2023-05-08 13:59 UTC, dmitrylala commented on tickets/t_dop05_full.tex
> +\sum_{n=1}^{\infty}\frac{(z-z_0)^{-n} }{(\rho-z_0)^{-n+1}}(+)$. Получается р-но.сх-ся ряд на $\text{Г}_2^{'}$ т.к мажорируется числовой прогрессией со знаменателем $\mu$. Равномерная сходимость (+) с
- Снова ссылки на формулы через '+' и '*' вместо \label и \ref
- На формулу '++' вообще нет ссылок, тогда и нет смысла ее вообще помечать, мб еще есть другие ненужные ссылки

2023-05-08 13:59 UTC, dmitrylala commented on tickets/t_dop05_full.tex
> +    \item Пусть $z_0$ – полюс $f(z)$, тогда в некоторой проколотой окрестности K точки z0 имеется представление $f(z)=\frac{c_{-k}}{(z-z_0)^k}+...+c_0+c_1(z-z_0)+...(3)$,
z0 -> z_0 должно быть, в других местах тоже

2023-05-08 15:41 UTC, Fedya2006 commented
pdf к доделанному full dop5
[t_dop5_full.pdf](https://github.com/dmitrylala/gos/files/11422558/t_dop5_full.pdf)

2023-05-14 17:31 UTC, Fedya2006 commented
Вроде все доделано

2023-05-14 20:49 UTC, dmitrylala requested changes
Будут те же проблемы с компиляцией, что и в PR #30. Скинь еще пж пдфки исправленной версии билета

2023-05-14 20:49 UTC, dmitrylala commented on tickets/t_dop05_big.tex
> +\usepackage{vmargin}
Та же проблема с компиляцией что и в PR #30

2023-05-14 20:49 UTC, dmitrylala commented on tickets/t_dop05_big.tex
> +\section{Ряд Лорана}
\section скорее всего будет тоже ломать компиляцию при встраивании в общую сборку

2023-05-14 22:08 UTC, Fedya2006 commented
[t_dop5_big.pdf](https://github.com/dmitrylala/gos/files/11473042/t_dop5_big.pdf)
[t_dop5_small.pdf](https://github.com/dmitrylala/gos/files/11473043/t_dop5_small.pdf)

2023-05-14 22:21 UTC, luseno4ek commented
small версия абсолютно нечитаемая, если нет вариантов нормально сократить, лучше вообще не добавлять ее в файл со шпорами 

![image](https://github.com/dmitrylala/gos/assets/75583244/bea79725-ff0b-425f-af6b-f90084b1308e)

2023-05-14 22:23 UTC, luseno4ek commented
Уменьшать размер формул **очень** не рекомендуется. при печати они будут вообще не видны,тк шрифт тоньше обычного

2023-05-14 22:29 UTC, Fedya2006 commented
> small версия абсолютно нечитаемая, если нет вариантов нормально сократить, лучше вообще не добавлять ее в файл со шпорами
> 
> ![image](https://user-images.githubusercontent.com/75583244/238212102-bea79725-ff0b-425f-af6b-f90084b1308e.png)

Особо не получится сократить иначе, по-моему, в случае глушилок на госах и палева лучше так, чем ничего. Представляю себя на месте человека с этим билетом без возможности скатать...

2023-05-14 22:33 UTC, luseno4ek commented
Если компилить в колонку, хотя бы формулы большие. но я за то, чтобы добавить переносы на новые строки, потому что это не понять тому, кто эту шпору не писал.
Лучше замечания выкинуть, доказательства заменить на идейную часть, но не оставлять в таком виде 

[t_dop05.pdf](https://github.com/dmitrylala/gos/files/11473071/t_dop05.pdf)

2023-05-14 22:36 UTC, Fedya2006 commented
> Если компилить в колонку, хотя бы формулы большие. но я за то, чтобы добавить переносы на новые строки, потому что это не понять тому, кто эту шпору не писал. Лучше замечания выкинуть, доказательства заменить на идейную часть, но не оставлять в таком виде
> 
> [t_dop05.pdf](https://github.com/dmitrylala/gos/files/11473071/t_dop05.pdf)

[t_dop5_small (2).pdf](https://github.com/dmitrylala/gos/files/11473081/t_dop5_small.2.pdf)
Так лучше?

2023-05-14 23:04 UTC, luseno4ek commented
> > Если компилить в колонку, хотя бы формулы большие. но я за то, чтобы добавить переносы на новые строки, потому что это не понять тому, кто эту шпору не писал. Лучше замечания выкинуть, доказательства заменить на идейную часть, но не оставлять в таком виде
> > [t_dop05.pdf](https://github.com/dmitrylala/gos/files/11473071/t_dop05.pdf)
> 
> [t_dop5_small (2).pdf](https://github.com/dmitrylala/gos/files/11473081/t_dop5_small.2.pdf) Так лучше?(замечание в док-вах используется)

 Залей, пожалуйста, код или скомпиль в колонку

2023-05-14 23:11 UTC, luseno4ek commented
Я пока не вникала в суть билета, сегодня голова уже не варит. Но в билетах, которые делали в 21 году ребята пятый билет не сильно большой и вполне себе может уместиться в шпору без сокращений. Посмотри его, пожалуйста, может, там лучше материал. Если что, я могу завтра посмотреть твой на предмет сокращений, напиши в вк, если надо будет помочь

[t_05_old.pdf](https://github.com/dmitrylala/gos/files/11473134/t_05_old.pdf)

2023-05-15 00:03 UTC, Fedya2006 commented
> Я пока не вникала в суть билета, сегодня голова уже не варит. Но в билетах, которые делали в 21 году ребята, пятый билет не сильно большой и вполне себе может уместиться в шпору без сокращений. Посмотри его, пожалуйста, может, там лучше материал. Если что, я могу завтра посмотреть твой на предмет сокращений, напиши в вк, если надо будет помочь
> 
> [t_05_old.pdf](https://github.com/dmitrylala/gos/files/11473134/t_05_old.pdf)

[t_dop16_tex.pdf](https://github.com/dmitrylala/gos/files/11473236/t_dop16_tex.pdf)

2023-05-15 00:22 UTC, Fedya2006 commented
> Я пока не вникала в суть билета, сегодня голова уже не варит. Но в билетах, которые делали в 21 году ребята, пятый билет не сильно большой и вполне себе может уместиться в шпору без сокращений. Посмотри его, пожалуйста, может, там лучше материал. Если что, я могу завтра посмотреть твой на предмет сокращений, напиши в вк, если надо будет помочь
> 
> [t_05_old.pdf](https://github.com/dmitrylala/gos/files/11473134/t_05_old.pdf)
[t_dop5_small (3).pdf](https://github.com/dmitrylala/gos/files/11473275/t_dop5_small.3.pdf)

2023-05-15 11:18 UTC, dmitrylala approved these changes

2023-05-15 11:18 UTC, merged