Ticket osn24
dmitrylala/gos pull request #7
Opened 2023-05-08 19:33 UTC by alsugiliazova

2023-05-09 10:34 UTC, dmitrylala requested changes
Затесался 23 билет + нужна пдфка

2023-05-09 10:34 UTC, dmitrylala commented on tickets/t_osn23.tex
См. PR #2, сюда затесался 23 билет

2023-05-09 10:34 UTC, dmitrylala commented on tickets/t_osn24.tex
Можешь пж отрендеренную пдфку в conversation добавить

2023-05-09 15:49 UTC, alsugiliazova commented
[t_osn24.pdf](https://github.com/dmitrylala/gos/files/11433047/t_osn24.pdf)

2023-05-09 15:49 UTC, alsugiliazova commented on main_big.tex
> +\include{tickets/t_osn23}
че-то да, че-то не поняла как так вышло

2023-05-09 15:50 UTC, alsugiliazova commented on tickets/t_osn24.tex
> Можешь пж отрендеренную пдфку в conversation добавить
Добавила

2023-05-10 11:39 UTC, dmitrylala requested changes
Основные поинты:
- оч много текста (для большой версии билета покатит)
- в main_small пока лучше не инклюдить

2023-05-10 11:39 UTC, dmitrylala commented on main_big.tex
> +\include{tickets/t_osn23}
Из этой бранчи его лучше удалить, исходник и инклюд

2023-05-10 11:39 UTC, dmitrylala commented on main_small.tex
> +\input{tickets/t_osn24}
Судя по тому, что билет вышел на ~7 страниц, в main_small он не влезет, так что придется либо сделать сокращенную версию, и инклюдить ее в main_small, либо не инклюдить пока что вовсе)

2023-05-10 11:39 UTC, dmitrylala commented on tickets/t_osn24.tex
> +Разберёмся, как будет работать такая модель в случае, если $D=1$. То есть у наших объектов есть ровно один численный признак, по которому они отличаются. Теперь наша линейная модель будет выглядеть с
Текста оч много на самом деле; для развернутой версии билета это мб даже и к лучшему, оч понятно читается; с другой стороны, для small версии имеет смысл ввести какие-то обозначения и столько текста просто опустить

2023-05-10 11:39 UTC, dmitrylala commented on tickets/t_osn24.tex
> +Всегда ли решение задачи регрессии единственно? Вообще говоря, нет. Так, если в выборке два признака будут линейно зависимы (и следовательно, ранг матрицы будет меньше $D$), то гарантировано найдётся
Про мотивацию введения регуляризации, если сокращать, можно в целом просто буллетами пояснить по пунктам; также мб имеет смысл посмотреть что было в наших презентацих по машинке на 3 курсе, там скорее всего уже достаточно ужато и расписано по пунктам тезисно, вот та [репа](https://github.com/MSU-ML-COURSE/ML-COURSE-21-22)

2023-05-14 18:56 UTC, alsugiliazova commented
[osn23_short.pdf](https://github.com/dmitrylala/gos/files/11472709/osn23_short.pdf)

2023-05-14 18:57 UTC, alsugiliazova commented on tickets/t_osn24.tex
> +Всегда ли решение задачи регрессии единственно? Вообще говоря, нет. Так, если в выборке два признака будут линейно зависимы (и следовательно, ранг матрицы будет меньше $D$), то гарантировано найдётся
Туда лучше не лезть, там четко по пунктам после 10 слайдов математики без которых эти пункты фиг поймешь

2023-05-16 19:58 UTC, luseno4ek approved these changes
билеты уменьшены, теперь имеют след вид 
[osn23-24_small.pdf](https://github.com/dmitrylala/gos/files/11491576/gos_main____.3.pdf)

2023-05-16 20:27 UTC, dmitrylala approved these changes

2023-05-16 20:27 UTC, merged